Repository sensity-ai/dot, pull requests merged in 2022-06, with the labels that each got.

#19 Update README to Download Models from Github Release Binaries
  README.md
  envs/environment-cpu.yaml
  envs/environment-gpu.yaml
Labels: documentation, assets, dependencies

#16 Update README + Add Github Templates
  .github/ISSUE_TEMPLATE/ask_a_question.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  README.md
  dot/__init__.py
Labels: documentation, ci/cd

#18 Verify camera ID when running dot in camera mode
  dot/__main__.py
  dot/commons/camera_utils.py
  dot/commons/model_option.py
  tests/pipeline_test.py
Labels: feature

#17 Add Feature to Use Config Files
  .github/workflows/code_check.yaml
  README.md
  configs/faceswap_cv2.yaml
  configs/fomm.yaml
  configs/simswap.yaml
  configs/simswaphq.yaml
  docs/run_without_camera.md
  dot/__main__.py
Labels: documentation, feature

#28 Update python version to 3.8
  .github/workflows/build_dot.yaml
  envs/environment-cpu.yaml
  envs/environment-gpu.yaml
  setup.cfg
Labels: dependencies

#27 Requirements changes now trigger CI
  .github/workflows/build_dot.yaml
  CHANGELOG.md
Labels: ci/cd

#29 Fix python3.8 pip cache location in CI
  .github/workflows/build_dot.yaml
  CHANGELOG.md
  README.md
Labels: ci/cd

#26 Fix `--save_folder` CLI Option
  docs/run_without_camera.md
  dot/commons/model_option.py
Labels: bug

#31 Add contributors list
  CHANGELOG.md
  README.md
Labels: documentation
